# Problems with pandas and date index

I had a lot of problems getting a single row out of a date indexed dataframe.  I was trying to access the row by `dataframe['2020-02-14']` but kept getting a keyerror.  Slices would work, `dataframe['2020-02-01':'2020-02-14']`.  I needed to use the .loc method as shown below.

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt

In [2]:
date_range = pd.date_range(dt.date(2020,1,1),dt.date(2020,4,1), freq='D')

In [10]:
date_range

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01',
               '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05',
               '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09',
               '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13',
               '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17',
               '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21',
               '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25',
               '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29',
               '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04',
               '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08',
               '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12',
               '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16',
               '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20',
               '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24',
               '2020-03-25', '2020-03-26', '2020-03-27', '2020-03-28',
               '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01'],
              dtype='datetime64[ns]', freq='D')

In [3]:
ds1 = np.random.randn(len(date_range))
ds2 = 10 * np.random.randn(len(date_range))

In [4]:
edf = pd.DataFrame(None, index=date_range)
edf['ds1'] = ds1
edf['ds2'] = ds2

In [5]:
edf

                 ds1        ds2
2020-01-01  3.032183  -8.997337
2020-01-02 -2.784267  12.616093
2020-01-03 -1.495920  16.894699
2020-01-04  0.277862 -11.730900
2020-01-05  0.586751  -3.208094
...              ...        ...
2020-03-28 -0.038629  -7.697855
2020-03-29  0.063652  -8.066420
2020-03-30  0.402882  29.969620
2020-03-31 -0.702255 -10.182245
2020-04-01  0.001601   9.268435

[92 rows x 2 columns]

In [6]:
edf['2020-02']

                 ds1        ds2
2020-02-01  2.196824  -0.701946
2020-02-02  0.258266  10.066734
2020-02-03  0.926778 -13.499069
2020-02-04  1.840846   5.873895
2020-02-05 -0.390373  17.543194
2020-02-06 -1.442858 -12.197421
2020-02-07  0.038583   2.976942
2020-02-08  0.360191   2.055763
2020-02-09  1.298128   0.137796
2020-02-10  0.497650   3.621535
2020-02-11  1.537348  -4.521037
2020-02-12 -0.524675  10.032604
2020-02-13 -1.470687   5.310223
2020-02-14  0.220051   3.949329
2020-02-15 -1.922086 -12.370448
2020-02-16  0.026109 -16.038085
2020-02-17  0.087651  -2.685280
2020-02-18 -0.846610  -4.944380
2020-02-19 -1.171253  -6.915566
2020-02-20  0.921408 -27.496063
2020-02-21 -0.005979 -12.760540
2020-02-22 -0.871498  -3.608508
2020-02-23  0.621349 -14.151212
2020-02-24 -0.703664   2.029807
2020-02-25  0.223193  -2.681057
2020-02-26  0.456961  -7.408726
2020-02-27  0.110985  -6.465660
2020-02-28 -0.906118  -5.396846
2020-02-29 -1.783777  -1.209597

In [7]:
edf['2020-02-15']

KeyError: '2020-02-15'

In [8]:
edf['2020-02-15':'2020-02-20']

                 ds1        ds2
2020-02-15 -1.922086 -12.370448
2020-02-16  0.026109 -16.038085
2020-02-17  0.087651  -2.685280
2020-02-18 -0.846610  -4.944380
2020-02-19 -1.171253  -6.915566
2020-02-20  0.921408 -27.496063

In [9]:
edf['2020-02-15':'2020-02-15']

                 ds1        ds2
2020-02-15 -1.922086 -12.370448

In [11]:
edf.loc['2020-02-15']

ds1    -1.922086
ds2   -12.370448
Name: 2020-02-15 00:00:00, dtype: float64